# main.yml
# This workflow will install Python dependencies, lint using Black, run tests using Pytest 
# and deploy the FastAPI app to Heroku
name: fastapi-github-actions-test

on: 
  # Trigger the workflow on a push event to any branch
  push: 
    branches: ['**']

# A workflow job running sequentially
jobs:
  build:
    # runs-on: defines The workflow runner
    runs-on: ubuntu-latest 
    # steps: defines a series of tasks executed by the Job
    steps:
    - uses: actions/checkout@v2
    - run: |   # To fetch all history for all tags and branches
        git fetch --prune --unshallow  

    #Task for setting up Python 3.11 using actions/setup-python@v2 Github action
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11 # Modify python version HERE

    #Task for installing dependencies, multi-line command
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black pytest
        if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi
